field: 2e6cab1b-36c2-4f7a-8170-52cf126ef42c # Two Columns
fieldLayouts:
  30894ea0-238c-412e-b152-4f8b7e511cb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c0c0905-47df-4869-9123-0b79178ddef0 # Left Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1a8a571-a96e-418a-81fb-fd010207f8ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06d7b5cb-3803-4f07-8c6f-cd8b4f253f40 # Right Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6ca8d82-e4be-4706-8184-dd57ae39f1e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9127da7c-a661-4949-bb7b-5d30f4a4e6b3
        userCondition: null
fields:
  3c0c0905-47df-4869-9123-0b79178ddef0: # Left Content
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: leftContent
    instructions: null
    name: 'Left Content'
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings:
        __assoc__:
          -
            - availableTransforms
            - '*'
          -
            - availableVolumes
            - '*'
          -
            - cleanupHtml
            - true
          -
            - columnType
            - text
          -
            - configSelectionMode
            - choose
          -
            - defaultTransform
            - ''
          -
            - manualConfig
            - ''
          -
            - purifierConfig
            - ''
          -
            - purifyHtml
            - '1'
          -
            - redactorConfig
            - ''
          -
            - removeEmptyTags
            - '1'
          -
            - removeInlineStyles
            - '1'
          -
            - removeNbsp
            - '1'
          -
            - showHtmlButtonForNonAdmins
            - ''
          -
            - showUnpermittedFiles
            - false
          -
            - showUnpermittedVolumes
            - false
          -
            - uiMode
            - enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  06d7b5cb-3803-4f07-8c6f-cd8b4f253f40: # Right Content
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: rightContent
    instructions: null
    name: 'Right Content'
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings:
        __assoc__:
          -
            - availableTransforms
            - '*'
          -
            - availableVolumes
            - '*'
          -
            - cleanupHtml
            - true
          -
            - columnType
            - text
          -
            - configSelectionMode
            - choose
          -
            - defaultTransform
            - ''
          -
            - manualConfig
            - ''
          -
            - purifierConfig
            - ''
          -
            - purifyHtml
            - '1'
          -
            - redactorConfig
            - ''
          -
            - removeEmptyTags
            - '1'
          -
            - removeInlineStyles
            - '1'
          -
            - removeNbsp
            - '1'
          -
            - showHtmlButtonForNonAdmins
            - ''
          -
            - showUnpermittedFiles
            - false
          -
            - showUnpermittedVolumes
            - false
          -
            - uiMode
            - enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: columns
name: Columns
sortOrder: 1
