field: 876c86b2-cb6f-4641-8c5b-30c64d43f934 # Left Column
fieldLayouts:
  c338cc20-352b-45f7-8e04-bc004fedf69a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fbb2efa0-366e-4b12-9981-03525862552e # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc707e85-a650-4e05-ae48-f72300ac4309
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07b9f3c3-13eb-471c-86f6-7672d4dfebf7 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3c710ec-33c2-4a4a-b13f-f29526999473
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e31b25f3-f5bc-4316-87e4-f31c692f9b36
        userCondition: null
fields:
  07b9f3c3-13eb-471c-86f6-7672d4dfebf7: # Link
    columnSuffix: ydoysude
    contentColumnType: text
    fieldGroup: null
    handle: ctaLink
    instructions: 'The fully qualified URL including ''https://''.'
    name: Link
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fbb2efa0-366e-4b12-9981-03525862552e: # Text
    columnSuffix: ipsqexwl
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ctaButton
name: 'CTA Button'
sortOrder: 4
