field: 29496a6c-2d9b-4895-8c36-2039cd24b17e # Right Column
fieldLayouts:
  6d00767c-d1d4-4d7e-a50e-23e1c15cbd00:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bd97e256-62e2-450a-abc3-41aad0fa0ccb # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79ab782f-8d35-4eb9-8390-c1d68f256b11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbb16297-051c-4562-81b3-4310f0cb9da0 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afeb8368-ef1e-4134-81fb-cd024f300248
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56328c71-fd72-42c1-90ba-b8e2a9c817cf
        userCondition: null
fields:
  bd97e256-62e2-450a-abc3-41aad0fa0ccb: # Text
    columnSuffix: opecfezx
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbb16297-051c-4562-81b3-4310f0cb9da0: # Link
    columnSuffix: kvdwedho
    contentColumnType: text
    fieldGroup: null
    handle: ctaLink
    instructions: 'The fully qualified URL including ''https://''.'
    name: Link
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ctaButton
name: 'CTA Button'
sortOrder: 4
