field: f3df398a-d517-4cbe-b154-bbb0230746da # Full Width CTA
fieldLayouts:
  fe4b1704-0a7b-469e-8b79-6db008dc5c6e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0225b6d8-ebe9-42c0-9b48-517ce7e2901d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d2e83e8-6344-4e15-a7c2-3d55c77c0dd7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 99bda947-506c-477b-8cdc-bf6ea2d0ff8d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 097e5ef4-f7a3-4b14-abfb-c087a7544ccd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12d2cbac-c1f0-4a53-a563-a9a158162cba # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef5dc9b6-2f14-4bc2-8257-f9c57f59f26d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23af17c6-783a-4769-a4b0-30ae22a5da22
        userCondition: null
fields:
  12d2cbac-c1f0-4a53-a563-a9a158162cba: # Button Link
    columnSuffix: wsbcbhgt
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: 'Link to form or other action.'
    name: 'Button Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  99bda947-506c-477b-8cdc-bf6ea2d0ff8d: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  0225b6d8-ebe9-42c0-9b48-517ce7e2901d: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
