field: 876c86b2-cb6f-4641-8c5b-30c64d43f934 # Left Column
fieldLayouts:
  16425194-3674-4246-b00e-e614ae8897b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53d976ba-eaea-401d-bc07-d048828c44a6 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16522885-5dd3-48a8-9c43-0916907af52f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 463fc305-0152-45ce-b85e-27d70ed8f780
        userCondition: null
fields:
  53d976ba-eaea-401d-bc07-d048828c44a6: # Header
    columnSuffix: sxslblpe
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: null
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: header
name: Header
sortOrder: 1
