field: 462fb273-74f3-4570-bd84-03a9098c5e31 # FAQ
fieldLayouts:
  ab1c8fcd-3182-462e-9529-a2a8cba304f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 007394ea-f95b-4d5d-a291-eda4df8659e0 # Question
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b285ab6-73b7-415b-be9b-1974be6b7c05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ee38eeb-8713-4aeb-b531-049d233c78fe # Answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95b46536-a731-489f-b90a-fb63caae4cf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83bfab3f-8f35-46de-877c-e762a569617d
        userCondition: null
fields:
  6ee38eeb-8713-4aeb-b531-049d233c78fe: # Answer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: null
    name: Answer
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  007394ea-f95b-4d5d-a291-eda4df8659e0: # Question
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: null
    name: Question
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: question
name: Question
sortOrder: 1
