field: 06f53f9c-c9f2-4452-89d4-8cfe045a5cef # Page Builder
fieldLayouts:
  6f85b9d1-2e2c-4c46-b83d-62ba72cd2c21:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 962d6eb5-bd48-427a-b80e-fb61b587cc16 # Left Column
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb2f68d2-ccb5-4d24-be95-1823a4834a02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b83f5b79-6c63-4a8c-98ae-0661d6fe8965 # Right Column
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3fe13bf-6e14-406f-98fa-d48dfe3d571d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac55863c-dffd-4f8e-aa42-a5d9aaa2dc6b
        userCondition: null
fields:
  962d6eb5-bd48-427a-b80e-fb61b587cc16: # Left Column
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: leftColumn
    instructions: null
    name: 'Left Column'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: a0e368cb-9d8f-427e-bb9a-fe91b8848733 # Less Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  b83f5b79-6c63-4a8c-98ae-0661d6fe8965: # Right Column
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: rightColumn
    instructions: null
    name: 'Right Column'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: a0e368cb-9d8f-427e-bb9a-fe91b8848733 # Less Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: twoColumns
name: 'Two Columns'
sortOrder: 1
