fieldLayouts:
  8ba97df9-2878-4d3d-9013-da9d5a1847b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f8c6dc7-216e-41f6-b060-b34bcdea3c60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18453672-590b-479a-ac12-b68902980efb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54cce44f-eb7e-4b4d-abff-dad62c5e5a4d
        userCondition: null
handle: bookings
hasTitleField: true
name: Bookings
section: 0ec10247-de60-40f9-a891-f06dc34d99d5 # Bookings
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
