fieldLayouts:
  541cf345-be33-4a6d-a761-85bf055225f9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 36cf9563-3320-44e6-9d78-7e56752fbde8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0eb73179-957c-4167-af47-81d8e8c339fb # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1b9e5f9-fbae-42b0-b61f-d832d68891be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5af23309-3392-4b94-8c9c-68b2e0d14e54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2cd58d-4f41-4bdc-a438-8c14445d0115
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ea7e00b-85d5-4f71-80e8-8f6dad4ac60f # Page Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e981f99-cabe-43f3-a296-e94797bc5d17
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8474227b-1deb-4e6d-b84d-ba77769c1c7c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 24907884-0f61-4170-86f9-fb5e19a65286 # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
