fieldLayouts:
  276d6d5e-7c29-4bac-ae53-fcec8900239a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ac9e967b-5298-4c02-9d54-e6b8688d848f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7cee913-b0e8-47e2-bc53-d3f6852bcfe6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 232d0659-2c1a-4294-a59a-345b78dcd1b3 # Resource Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 730e6725-0e21-4cc3-a931-549c9f4cca2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f10b940-dc15-4def-8620-0c3ddb1c5026
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e0436cd-3558-4eb3-984a-ecf0ff46fd79
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 61b46e8f-a3fa-4e30-a8ea-8b8b4125b77d # Maps
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
