fieldLayouts:
  504c9ba7-f9a9-4b05-920c-703543513f34:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ce17ec9b-2158-4338-8932-b1d2f26452ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a050fba1-ae11-4377-ad21-9d23512f62dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 351fbeb8-08ab-4123-83e1-0ab7948deb4c # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4ef4a2f-8d16-49a7-9033-e33a5cbc9e50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bb78f1e-fa2e-472c-9a67-71ed42d5fb10
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6be3c218-cb3f-4fe6-b053-d244f17578ba # Audio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae1fbc4-252e-413c-b905-cf903c9b3a3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9ca2ff0-0116-44ce-9c8b-7559b0da835b # Transcript
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 551dc74e-8ac5-4798-baaa-d53fdbf04717
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 97a3d13b-e5ff-4706-a146-1ed0a83f7766
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 1f2f0b85-84dd-4cb7-996f-cfc1f7478721 # Native Plants Tour
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
