fieldLayouts:
  45b8dd43-b9d2-4988-9384-b5efcf74581d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Fall 1998, Summer 2000, etc.'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d661127-bec0-433c-b57a-78f0478331a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2355853-0b3a-451c-bc58-915c397e7a06 # Volume
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7fa8ee1-a1db-4f19-9db4-1f5c6a444098
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 18b2da16-3aa7-4cfc-abb2-84832d2cf5f5 # Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0370266a-d7bd-4225-91f9-b1c19ad1cf2a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 31059278-fbc1-4257-bc3e-db4adaf39246 # Newsletter PDF
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c2951bb-51c3-4bb0-9028-fd485f7bd9d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ba270839-1b30-4d37-a57a-c2571fd86fa5 # PDF Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8085627-1d26-4014-b8da-87af1b4afa36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: Notes
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 343e60b6-0523-4ad4-8b3d-67aaad641b52
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f0da64a-f1da-47be-a4de-8a099752b9d1
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 3562ff77-b843-496b-898e-d8bae315e570 # Newsletter
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
