fieldLayouts:
  4798f0d9-eee6-4423-a447-11072df0e8b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 964202ae-717c-477a-ae1a-e5477dccdacb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9241074-1c79-4b26-92c6-a3cb08a36175
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8363c321-873b-43f6-b98c-b68ff1b869d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ea7e00b-85d5-4f71-80e8-8f6dad4ac60f # Page Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1183e90e-5ef4-4f0f-906c-799c66017d49
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2650681-3773-478d-8e31-5f18782cafd6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 45b6bf49-7b18-41ba-bb19-f451420a19f3 # Collections
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
