fieldLayouts:
  05fc07d3-a419-44fa-ad0c-57c61d64a1b1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50df45bd-1160-4b9a-b7d5-ff9706817f14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73a9e7c8-a3ee-4127-831f-cfe8485f80d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ea7e00b-85d5-4f71-80e8-8f6dad4ac60f # Page Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cd5c2d6-2680-41a5-80f5-223cd9d933a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7dc99a22-7b3f-4011-ba61-9ba5f6a9d398
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: e16e1677-c1c6-4584-9a04-55c202f2cbf8 # Gallery
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
