fieldLayouts:
  49011583-561b-4f45-892b-f3cecefe941e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 05872734-ef83-4e39-abba-d5d23b6120fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9663b8e6-5b8c-4a2f-8050-9da6bbd9450a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93fafdb0-c999-4f86-882d-8f0acf7d4cbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b4a96df2-9645-4f49-a6e8-0e4a4b3be858 # Resource Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2041d46-ac40-42aa-ad53-a855313ad659
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f75561a-8855-42d9-8eaa-08c3140c0da7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7d2f1d61-50b5-41ad-9814-fb33aa21a00f # Map
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
