fieldLayouts:
  046c3458-afad-4754-8344-a0d9a1269f00:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ec16e06b-0ab6-436e-91f5-a5fc702dd0a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea0f14f7-38cc-4763-a0c5-fbc6c70c1451 # Issue
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeb29854-660a-4fcb-97d5-2924725db60f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5f71f48-c3de-4bed-9d01-12883d5d47ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d1afefd-6011-4b8d-86c5-78b3b2fcb9d6 # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02c0653a-6322-4ae8-afb8-4bfaed945d42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 567a2641-792c-4357-962f-c508b5f5486c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ea7e00b-85d5-4f71-80e8-8f6dad4ac60f # Page Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26deb3e3-6545-4632-acb2-0327213e4d87
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4a985ff-5927-4112-8312-7bd23ee8e28d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 762300b5-fa76-4ba6-ac94-33ec53c50db6 # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
