fieldLayouts:
  25cb14d0-9976-46a5-a9a7-d939937826db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2db1a49d-fd4e-4286-8f53-a2a8759fbcf9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c96979d2-5bcd-4616-ac69-55f344bd9c8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f2244d9-92f7-43de-a68e-f650e31f255c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 462fb273-74f3-4570-bd84-03a9098c5e31 # FAQ
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ace7d407-b2f4-472c-9285-ab52b3d07bf1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48371b8a-43b0-478c-85bc-132d31545f22
        userCondition: null
handle: faq
hasTitleField: true
name: FAQ
section: 73e6f389-874a-42a1-8d01-a2b6dc9d021e # FAQ
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
