fieldLayouts:
  ac63cdae-1932-406f-8e33-77829755bdf2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d0953044-7462-4cdc-9525-9c8bf47f2680 # Front Page Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85b18ae7-155a-425a-bbc2-9e038e13331f
            userCondition: null
            warning: null
            width: 100
        name: 'Hero Slideshow'
        uid: 2a357b8a-3c14-46f0-854d-314dffeb8a03
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7021fdf1-b8c3-47c8-b68c-b171759845c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d7b8773-ed1d-47bd-9e1e-11cf57d4ff45 # Home Triptych
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3da03774-1232-4620-aa4e-3a50a9311b74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ea7e00b-85d5-4f71-80e8-8f6dad4ac60f # Page Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08675578-f869-48b8-ba02-e297a6115c1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9cae43d-ddf3-42a4-9883-5856d62ce973
        userCondition: null
handle: homePage
hasTitleField: false
name: 'Landis Arboretum (HOME)'
section: d88a6933-19d2-42a9-b9f0-3ce161f74d40 # Landis Arboretum (HOME)
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
