fieldLayouts:
  93a378e9-37d6-41aa-aa73-ed208e9f724c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e31fd175-f5be-47eb-aa8d-7554ee45bd2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b82be61-a57b-440a-8a47-6e00b1bfb060
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 244f1c51-4d13-42eb-bb61-6d6af52b851a
        userCondition: null
handle: mapsIndex
hasTitleField: true
name: 'Maps Index'
section: 3e73de84-059d-4ef8-9c53-18257b6f3698 # Maps Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
