fieldLayouts:
  3c42c393-b5fd-4349-8db6-c3ddd7e8efc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7690d2c-83e4-44d1-9e39-fb4ff3397276
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f78ff8ec-22da-4013-8754-8889f07c9fe6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0eb73179-957c-4167-af47-81d8e8c339fb # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df63ba10-6324-4818-aeaa-6301b1faaaa8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1f464e1-0e6d-4353-bc56-6311584db0a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba68e361-b34a-48c2-a58c-315fb7ab6fe4
        userCondition: null
handle: maps
hasTitleField: true
name: Maps
section: 433b6d9e-7282-4d08-aecf-76961050bbdd # Maps
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
