fieldLayouts:
  619c517d-7e30-429c-ad5b-8d48751eb289:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e2705b04-1ebb-484f-aa0a-5cb3f0713c1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15a830a3-6cd3-4f26-926f-2dc75581b1c8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7fd0e1d4-b28e-4b10-8fc8-de0f0ad4dee4
        userCondition: null
handle: newsArchive
hasTitleField: true
name: 'News Archive'
section: 09999c37-886a-43ea-be0c-8a6105114c6b # News Archive
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
