fieldLayouts:
  19b9a59d-19a4-46fe-b0c7-fc32f219956a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8aeac135-499e-4295-a996-999f6a20bfb0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0eb73179-957c-4167-af47-81d8e8c339fb # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3a410c0-9a43-4536-a530-a1584bc891ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 065a25c4-25c8-497d-8a1e-d88cda9b4dc3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76ae296b-ac19-40b5-857f-df2d04264bf6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06f53f9c-c9f2-4452-89d4-8cfe045a5cef # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5e4099-1966-4e5f-bf7e-974df143bff8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 38ab0da6-066d-4f52-9f7a-c24b6e4cfca9
        userCondition: null
handle: rentals
hasTitleField: true
name: Rentals
section: 8a02040d-73e9-4f22-9894-8e4a86b1fe9b # Rentals
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
