fieldLayouts:
  a14480db-eda0-4a38-9be8-3fbf3d7e57cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00205317-684b-4005-b94f-8dac25da9a96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa7d012-4c99-40f1-ae22-a6a1f6b7ff9c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39b70544-dd33-4c7d-86fc-026d32e7b0f1
        userCondition: null
handle: siteContact
hasTitleField: true
name: 'Site Contact'
section: 248386fe-8099-4726-908b-b085800c794a # Site Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
