fieldLayouts:
  0ca3fa9c-89a0-46ef-80a9-a01cd52c2035:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7ba03b49-037c-468f-87b1-d85bd61cd6a5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7238555-6367-417d-b706-000f3833004e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c11a70d2-ab50-462e-8058-835449ec25c2 # Sponsor Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2987ea5-7002-44c8-8748-f9031769e4b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37bbea00-9f3f-4557-b6ab-a908e66c2d21
        userCondition: null
handle: sponsors
hasTitleField: false
name: Sponsors
section: af5c675a-209c-402a-9952-31e471fce849 # Sponsors
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
