fieldLayouts:
  383a22ad-b82a-4f29-a315-c729992e2294:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2384ac27-9451-4613-9739-7430caca4704
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76ed9077-0f92-4dc0-b3ff-c772483f67ec # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23000b14-4b31-4309-9874-5091e2a399f9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bed4b7f-a50f-4ef8-909f-a42d7ef058f5
        userCondition: null
handle: videoIndex
hasTitleField: false
name: 'Video Index'
section: 10594ad3-f572-4f30-bd7e-da05df72092c # Video Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
