fieldLayouts:
  33f9ba59-86dd-4777-b625-b58f98979bca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df2351e8-2cc9-49f2-ad85-53c5c1ba4d0b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9107c545-c726-47b7-8637-37caff064f9f # Left Column
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 242bca06-ad51-4d92-b19b-e993f9bdc58a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b09d30a2-6a31-4725-89bf-5a94292a5de3 # Right Column
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae69d925-dc2e-4ccd-aa62-22ca2e152f85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05bd9797-ac54-4c82-bfe4-2031858c4832
        userCondition: null
handle: visit
hasTitleField: false
name: 'Vist Landis'
section: c5865b6a-7482-4a59-8212-4273ff47b853 # Vist Landis
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
