defaultPlacement: end
fieldLayouts:
  4f908a56-6664-488f-af54-3b7a02a48965:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: af6fd7c5-194b-41b1-9be6-5266cd1772b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d00a830-216b-4f32-8860-c1eddd638719 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5535cc1e-1319-4ec0-a96e-c00564b4c2db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2355853-0b3a-451c-bc58-915c397e7a06 # Volume
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85494de7-d96f-4d7a-ba30-cd70c57beeee
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 18b2da16-3aa7-4cfc-abb2-84832d2cf5f5 # Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bf1e883-6e3b-499a-b34e-c5de23c75df6
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 7ebe93c6-167c-4681-bac0-2bc460ffc0f7
        userCondition: null
handle: category
name: Issue
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    hasUrls: true
    template: newsletters/_issue.twig
    uriFormat: 'issue/{slug}'
structure:
  maxLevels: null
  uid: 66df4af8-5ce9-42a4-a6bf-d76854e24fc4
