defaultPlacement: end
fieldLayouts:
  e314d05b-da6b-46bf-89b4-cb465ca6353a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5f476a8f-78b6-4096-803d-9ab353bb6366
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 410e3482-da36-4323-ba97-fc5f0c76dc46
        userCondition: null
handle: qrCodeTours
name: 'QR Code Tours'
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    hasUrls: true
    template: null
    uriFormat: 'qr-code-tours/{slug}'
structure:
  maxLevels: null
  uid: 1259fb5e-128b-4ea5-a637-3505d9e7761d
