fieldLayouts:
  4c4b586a-a36d-4e46-8a31-d798ca3194d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ce7f63bd-1055-4024-b426-f349aa025482
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51e871f9-41cb-4f8f-ad4c-29c51858aa74 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9d52b20-ef33-4185-89d2-0ee021fc5b15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbf66916-b8c6-486e-8a1e-940f98194059 # Optimized Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf265760-cf78-4a22-af72-a24d3dd5cdd8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8936e76-9a16-4826-bed0-89f9e810cba9 # Collection Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b039c4-3719-427c-9fda-1bda028f71ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63669ea8-0e6b-4627-b37e-e9e06fb5abef # Optimized Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 313ae00e-2915-41ad-9f17-cfcce2b9cced
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09bb8804-f7b4-4ffa-8090-96ae28e9ada3
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
