fieldLayouts:
  bad6de51-9205-4dcd-aac7-f382af96a712:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1c97d296-5ad6-492f-b93b-abb70c62d553
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0219c000-3ecd-46f1-8c72-75a314deca6e
        userCondition: null
fs: newsletters
handle: newsletters
name: Newsletters
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
