columnSuffix: null
contentColumnType: string
fieldGroup: 41c1d536-7cc0-4837-814d-a237f85db1f9 # Newsletters
handle: category
instructions: null
name: Issue
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: 'Select Issue'
  showSiteMenu: true
  source: 'group:c8e69821-c0b1-46fa-b608-c0e2c1ebe6d3' # Issue
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
