columnSuffix: prwpkwlo
contentColumnType: text
fieldGroup: c060adfd-ad0d-44ee-9598-933e4f598995 # Common
handle: collectionImages
instructions: null
name: 'Collection Images'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: false
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - images
        - '*'
  variants:
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '3'
        -
          - aspectRatioY
          - '4'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
