columnSuffix: prwpkwlo
contentColumnType: string
fieldGroup: c060adfd-ad0d-44ee-9598-933e4f598995 # Common
handle: collectionImages
instructions: null
name: 'Collection Images'
searchable: false
settings:
  errorMessage: 'Component class ''nystudio107\imageoptimize\fields\OptimizedImages'' belongs to a disabled plugin (ImageOptimize).'
  expectedType: nystudio107\imageoptimize\fields\OptimizedImages
  settings:
    __assoc__:
      -
        - displayDominantColorPalette
        - ''
      -
        - displayLazyLoadPlaceholderImages
        - ''
      -
        - displayOptimizedImageVariants
        - '1'
      -
        - fieldVolumeSettings
        -
          __assoc__:
            -
              - images
              - '*'
      -
        - variants
        -
          -
            __assoc__:
              -
                - width
                - '576'
              -
                - useAspectRatio
                - '1'
              -
                - aspectRatioX
                - '3'
              -
                - aspectRatioY
                - '4'
              -
                - retinaSizes
                -
                  - '1'
              -
                - quality
                - '82'
              -
                - format
                - jpg
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
