columnSuffix: null
contentColumnType: string
fieldGroup: c060adfd-ad0d-44ee-9598-933e4f598995 # Common
handle: fullWidthCta
instructions: null
name: 'Full Width CTA'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fullwidthcta}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
