columnSuffix: null
contentColumnType: string
fieldGroup: 41c1d536-7cc0-4837-814d-a237f85db1f9 # Newsletters
handle: newsletterPDF
instructions: 'PDF of newsletter and/or associated images.'
name: 'Newsletter PDF'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:19d84302-acf0-4f82-bb97-a7391fd042ed' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b183c135-db13-4f16-b821-c97699593618' # Newsletters
  restrictedLocationSubpath: null
  selectionLabel: 'Add PDF/Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
