columnSuffix: uhectmqq
contentColumnType: text
fieldGroup: 41c1d536-7cc0-4837-814d-a237f85db1f9 # Newsletters
handle: number
instructions: null
name: Number
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
