columnSuffix: zpwizkky
contentColumnType: text
fieldGroup: 60ef0d6d-98db-4d15-b7e7-a7334cbf9d9a # Events
handle: paypalButtonCode
instructions: 'The PayPal provided purchase button code.'
name: 'PayPal Button Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  columnType: null
  initialRows: 6
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
