columnSuffix: hcyfjxpb
contentColumnType: text
fieldGroup: c060adfd-ad0d-44ee-9598-933e4f598995 # Common
handle: subtitle
instructions: 'Page subtitle displayed in  header.'
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
