columnSuffix: lofyhcym
contentColumnType: string
fieldGroup: 32d6a11e-bf26-4a5a-82ba-3fa5348d8be7 # Audio Tour
handle: tourIntro
instructions: null
name: 'Tour Intro'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
  expectedType: craft\redactor\Field
  settings:
    __assoc__:
      -
        - availableTransforms
        - '*'
      -
        - availableVolumes
        - '*'
      -
        - columnType
        - text
      -
        - configSelectionMode
        - choose
      -
        - defaultTransform
        - ''
      -
        - manualConfig
        - ''
      -
        - purifierConfig
        - ''
      -
        - purifyHtml
        - '1'
      -
        - redactorConfig
        - ''
      -
        - removeEmptyTags
        - '1'
      -
        - removeInlineStyles
        - '1'
      -
        - removeNbsp
        - '1'
      -
        - showHtmlButtonForNonAdmins
        - ''
      -
        - showUnpermittedFiles
        - false
      -
        - showUnpermittedVolumes
        - false
      -
        - uiMode
        - enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
