currLabel: 'Clear Caches'
customIcon: null
enabled: true
handle: mmikkel/cpclearcache
icon: trash
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Clear Caches'
prevLevel: 1
prevParent: null
prevUrl: mmikkel/cpclearcache
sortOrder: 10
subnavBehaviour: null
type: null
url: mmikkel/cpclearcache
