currLabel: 'Plugin Store'
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: null
prevParent: null
prevUrl: plugin-store
sortOrder: 9
subnavBehaviour: null
type: craft
url: plugin-store
