currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: categories
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: null
prevParent: null
prevUrl: categories
sortOrder: 2
subnavBehaviour: null
type: craft
url: categories
