currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: null
prevParent: null
prevUrl: entries
sortOrder: 1
subnavBehaviour: null
type: craft
url: entries
