currLabel: Forms
customIcon: null
enabled: true
handle: forms
icon: null
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 2
newWindow: false
parent: 42f60538-2194-4b64-b3ae-ae1aa9890cb4
prevLabel: Forms
prevLevel: 2
prevParent: 42f60538-2194-4b64-b3ae-ae1aa9890cb4
prevUrl: freeform/forms
sortOrder: 6
subnavBehaviour: null
type: plugin
url: freeform/forms
