currLabel: Integrations
customIcon: null
enabled: true
handle: integrations
icon: null
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 2
newWindow: false
parent: 42f60538-2194-4b64-b3ae-ae1aa9890cb4
prevLabel: Integrations
prevLevel: 2
prevParent: 42f60538-2194-4b64-b3ae-ae1aa9890cb4
prevUrl: freeform/integrations
sortOrder: 10
subnavBehaviour: null
type: plugin
url: freeform/integrations
