currLabel: 'Plugin Settings'
customIcon: null
enabled: true
handle: plugin
icon: null
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 2
newWindow: false
parent: 264c781c-283f-4445-9041-51491c928fbb
prevLabel: 'Plugin Settings'
prevLevel: 2
prevParent: 264c781c-283f-4445-9041-51491c928fbb
prevUrl: seomatic/plugin
sortOrder: 19
subnavBehaviour: null
type: plugin
url: seomatic/plugin
