currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 22
subnavBehaviour: null
type: craft
url: settings
