currLabel: 'Site Settings'
customIcon: null
enabled: true
handle: site
icon: null
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 2
newWindow: false
parent: 264c781c-283f-4445-9041-51491c928fbb
prevLabel: 'Site Settings'
prevLevel: 2
prevParent: 264c781c-283f-4445-9041-51491c928fbb
prevUrl: seomatic/site/identity
sortOrder: 17
subnavBehaviour: null
type: plugin
url: seomatic/site/identity
