currLabel: 'Tracking Scripts'
customIcon: null
enabled: true
handle: tracking
icon: null
layout: db05d377-be2b-4a96-a920-7666d07afe21 # Default
level: 2
newWindow: false
parent: 264c781c-283f-4445-9041-51491c928fbb
prevLabel: 'Tracking Scripts'
prevLevel: 2
prevParent: 264c781c-283f-4445-9041-51491c928fbb
prevUrl: seomatic/tracking/gtag
sortOrder: 18
subnavBehaviour: null
type: plugin
url: seomatic/tracking/gtag
