defaultPlacement: end
enableVersioning: true
handle: birdBlog
name: 'Bird Blog'
propagationMethod: all
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    enabledByDefault: true
    hasUrls: true
    template: birdblog/_entry
    uriFormat: 'birding/{slug}'
type: channel
