defaultPlacement: end
enableVersioning: true
handle: eventsIndex
name: 'Upcoming Events'
propagationMethod: all
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    enabledByDefault: true
    hasUrls: true
    template: events/index
    uriFormat: events
type: single
