defaultPlacement: end
enableVersioning: true
handle: faq
name: FAQ
propagationMethod: all
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    enabledByDefault: true
    hasUrls: true
    template: faq.twig
    uriFormat: faq
type: single
