defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Landis Arboretum (HOME)'
propagationMethod: all
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
