defaultPlacement: end
enableVersioning: true
handle: mapItem
name: Maps
propagationMethod: all
siteSettings:
  ccdf06db-63d7-465e-8ec1-7ae2b8a1ad53: # Landis Arboretum
    enabledByDefault: true
    hasUrls: true
    template: maps/_entry.twig
    uriFormat: 'maps/{slug}'
structure:
  maxLevels: null
  uid: 54773cf4-2f1d-4c4b-b264-674cb2127417
type: structure
